/*
 * wheel-sim.js — drive the wheel notcher with each platform's real scroll
 * stream, deterministically, without that platform.
 *
 *   node tools/wheel-sim.js
 *
 * WHY THIS EXISTS
 * "The scroll animation doesn't show on Windows" is a bug nobody here can
 * reproduce and nobody here can watch being fixed, because nobody here has
 * Windows. What CAN be reproduced is the stream Windows sends, because it is
 * documented and because libuiohook's arithmetic on it is right there in
 * node_modules:
 *
 *   - a mouse wheel sends one message per click carrying a delta of 120, and
 *     libuiohook's get_scroll_wheel_rotation turns that into a rotation of ±1.
 *   - a Windows precision touchpad is an ultra-high-resolution device, and the
 *     documented default delta for one is 1. The same arithmetic — accumulate,
 *     divide by 120, keep the remainder — therefore emits rotation 0 for 119
 *     messages out of every 120, at the pad's full report rate.
 *
 * The second stream is what the cat could not cope with, so the second stream is
 * what is replayed here, generated by the same formula the C does rather than by
 * a guess at what it looks like.
 *
 * The clock is faked, like everywhere else in tools/: the notcher is a rate
 * limiter, and a test whose result depended on how fast the machine ran it would
 * pass or fail by accident.
 */
const assert = require("assert");
const { notchWheel } = require("../src/main/input.js");

const WHEEL_DELTA = 120;

/*
 * libuiohook's windows/input_helper.c, transcribed. The remainder carried
 * between calls is the whole reason a precision touchpad ever reports a
 * direction at all, so it has to be modelled rather than approximated.
 */
function rotator() {
  let acc = 0;
  return (delta) => {
    acc += delta;
    const value = Math.trunc(acc / -WHEEL_DELTA); // vertical is inverted on Windows
    acc = acc % WHEEL_DELTA;
    return value;
  };
}

/*
 * A notcher on a clock we own, plus a log of everything that reached the far
 * side of it. `at` is what the renderer would have been woken at.
 */
function rig() {
  const out = [];
  let t = 0;
  const notched = notchWheel((e) => out.push({ rotation: e.rotation, at: t }), () => t);
  return {
    out,
    now: () => t,
    // One raw message, `ms` after the previous one.
    send(rotation, ms = 0) {
      t += ms;
      notched(rotation);
    },
  };
}

// --- scenarios --------------------------------------------------------------
const results = [];
function check(name, fn) {
  try {
    fn();
    results.push(["PASS", name, ""]);
  } catch (err) {
    results.push(["FAIL", name, err.message]);
  }
}

/*
 * The bug. A precision touchpad reporting at 125Hz used to bat the yarn ball
 * 125 times a second, which pinned it against the edge of the canvas at maximum
 * speed for the whole gesture and re-kicked it before it could hop.
 */
check("a precision touchpad does not report faster than a wheel notches", () => {
  const r = rig();
  const rot = rotator();
  // Two seconds of a real two-finger drag: 125Hz, one ultra-high-resolution
  // unit per message, which is the documented Windows default.
  for (let i = 0; i < 250; i++) r.send(rot(1), 8);

  assert.ok(r.out.length > 0, "a two-finger drag reported nothing at all");
  assert.ok(
    r.out.length <= 44,
    `${r.out.length} reports in 2s — the firehose is still a firehose`
  );

  /*
   * A sliding window rather than a minimum gap, because one kind of report IS
   * allowed to arrive early: a whole notch goes straight through, and during a
   * long drag one of those turns up every 120 units. That is a handful a second
   * at most, so it cannot make the stream fast again — which is exactly what a
   * rate bound says and a gap bound cannot.
   */
  let worst = 0;
  for (let i = 0; i < r.out.length; i++) {
    const n = r.out.filter((e) => e.at > r.out[i].at - 500 && e.at <= r.out[i].at).length;
    worst = Math.max(worst, n);
  }
  assert.ok(worst <= 12, `${worst} reports inside one 500ms window`);
});

/*
 * Rate limiting alone would have been half a fix. The other half is that
 * rotation 0 says nothing about direction, so before this the renderer guessed —
 * and a guess that feeds back into itself ("keep going the way it is going")
 * never corrects.
 */
check("a touchpad's direction is learned, and it is the real one", () => {
  const r = rig();
  const rot = rotator();
  // Scrolling down: Windows sends negative deltas, and libuiohook inverts.
  for (let i = 0; i < 400; i++) r.send(rot(-1), 8);

  const directed = r.out.filter((e) => e.rotation !== 0);
  assert.ok(directed.length > 0, "400 units of travel and never once a direction");
  assert.ok(
    directed.every((e) => e.rotation > 0),
    `direction flipped mid-gesture: ${directed.map((e) => e.rotation).join(",")}`
  );
  // And once it is known it is not forgotten between notches.
  assert.ok(
    r.out.slice(-4).every((e) => e.rotation > 0),
    "the learned direction was dropped again"
  );
});

/*
 * The regression risk of the fix: a rate limiter that treats a wheel click like
 * a sub-notch step would make a plugged-in mouse feel laggy on every platform,
 * to fix a touchpad on one.
 */
check("a mouse wheel click is passed straight through, undelayed", () => {
  const r = rig();
  const rot = rotator();
  // Six clicks, 10ms apart — faster than the notch interval, and every one of
  // them a real notch that must not be dropped.
  for (let i = 0; i < 6; i++) r.send(rot(WHEEL_DELTA), 10);

  assert.strictEqual(r.out.length, 6, `${r.out.length} of 6 wheel clicks survived`);
  assert.ok(
    r.out.every((e) => e.rotation === -1),
    `a wheel click lost its direction: ${r.out.map((e) => e.rotation).join(",")}`
  );
  assert.strictEqual(r.out[5].at - r.out[0].at, 50, "a wheel click was held back");
});

check("reversing the wheel reverses the reports", () => {
  const r = rig();
  const rot = rotator();
  r.send(rot(WHEEL_DELTA), 10);
  r.send(rot(-WHEEL_DELTA), 10);
  assert.deepStrictEqual(
    r.out.map((e) => e.rotation),
    [-1, 1],
    "the wheel does not reverse"
  );
});

/*
 * A precision touchpad reports a resting finger's tremor. Batting the yarn ball
 * for that would have it twitching whenever a hand was on the pad.
 */
check("a stray sub-notch message is not a gesture", () => {
  const r = rig();
  r.send(0, 1000);
  r.send(0, 1000);
  assert.strictEqual(r.out.length, 0, "a resting finger scrolled the cat");
});

/*
 * Slowing a drag down must make the reports sparse, not stop them: the count
 * accumulates while the gate is shut rather than resetting, which is the same
 * rule evdev-linux.js uses for a Linux touchpad.
 */
check("a slow drag keeps reporting, just less often", () => {
  const r = rig();
  const rot = rotator();
  for (let i = 0; i < 30; i++) r.send(rot(1), 200); // one unit every 200ms
  assert.ok(r.out.length >= 9, `a slow drag stalled after ${r.out.length} reports`);
});

/*
 * Linux never goes through here — evdev-linux.js notches its own touchpad and
 * hands over whole ticks — but uiohook is also the source on X11 and macOS, and
 * a stream that was already well-formed must come out unchanged.
 */
check("an already-notched stream is untouched", () => {
  const r = rig();
  for (const v of [1, 1, -1, 2, -3]) r.send(v, 60);
  assert.deepStrictEqual(
    r.out.map((e) => e.rotation),
    [1, 1, -1, 2, -3],
    "a well-formed wheel stream was altered"
  );
});

// --- report -----------------------------------------------------------------
let failed = 0;
for (const [state, name, why] of results) {
  if (state === "FAIL") failed++;
  console.log(`${state === "PASS" ? "  ok  " : "  FAIL"}  ${name}${why ? `\n          ${why}` : ""}`);
}
console.log(`\n${results.length - failed}/${results.length} passed`);
process.exit(failed ? 1 : 0);
